### ISSUE TITLE
Hide Firebase apiKey using .env file

### ISSUE THREAD

**Issue by devzom** [ondrejpolach/ondrejpolach.cz#1]
It's worth to use Firebase apiKey within .env file and do not store it inside open file.

**Comment by ondrejpolach** [comment]
Thanks for your recommendation Jakub.

**Comment by devzom** [comment]
Good :) worth to remember about the risk and if apiKey usage is limited, to do not pay for a mistake :)

**Comment by ondrejpolach** [comment]
I know that. Hovewer Firebase config with apikey included should be secure to use on open environment. Firebase products have other layer of security based on security rules, so compromised apikey should not have big impact - from what I know about this. But I agree with you that env file during deployment is more secure that save in public github repo.
All the best Jakub :)
